behaviors:
  move_to_static_target_01:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_02:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_03:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_04:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 512
          num_layers: 1
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_05:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 256
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_06:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000

  
  move_to_static_target_07:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000

  
  move_to_static_target_08:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_09:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_10:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_11:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_12:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_13:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_14:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_15:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 5
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_16:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 5
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_17:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 5
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_18:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 7
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_19:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 7
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000


  move_to_static_target_20:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 7
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 128
          num_layers: 3
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 50000